name: tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    name: Testing with Erlang/OTP ${{ matrix.otp }}

    env:
      REBAR_PROFILE: test

    strategy:
      fail-fast: false
      matrix:
        otp: ["26.2.4", "25.3.2.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Erlang
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          rebar3-version: "3.22.1"
          version-type: strict
          install-hex: false

      - name: Set up efmt
        uses: bunopnu/use-efmt@v1.1.0
        with:
          version: "0.15.0"

      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: _build
          key: erlang-${{ matrix.otp }}-${{ hashFiles('**/rebar.lock') }}-build

      - name: Compile Project
        run: make build

      - name: Check Project
        run: make check

      - name: Test Project
        run: make test

      - name: Upload Coverage Reports
        run: rebar3 coveralls send
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
